name: Docker and Terraform

on: [workflow_dispatch]

jobs: 
  build-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: metrics-exporter
      PROJECT_ID: silicon-synapse-372206
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{secrets.GOOGLE_CREDENTIALS}}
        project_id: ${{env.PROJECT_ID}}
        export_default_credentails: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
    
    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        
  terraform:
    needs: build-push-gcr
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terrafrom Init
      run: terraform init
      env:
        GOOGLE_CREDENTAILS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: Terrafrom Format
      run: terraform fmt -check

    - name: Terrafrom Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTAILS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTAILS: ${{secrets.GOOGLE_CREDENTIALS}}